### ISSUE TITLE
Nixpkgs on package info?

### ISSUE THREAD

**Issue by klarkc** [purs-nix/purs-nix#27]
Because nix flake only allow pure imports, it's not possible to import nixpkgs in a package.nix file, so its usage is pretty limited. I fixed it by adding [pkgs on info arguments](https://github.com/LovelaceAcademy/purs-nix/commit/fc8446e68a92de3ec6c5a0234acf7f21c82cd257), and it worked for me, allowing me to [use nixpkgs on it](https://github.com/LovelaceAcademy/cardano-transaction-lib/blob/234a2bffe8a39911aa638bcb788e1a4c625320b4/package.nix) Should I submit a PR?

**Comment by ursi** [comment]
I didn't know there was any effort to port ctl over, so that's cool to see!

So I have considered this issue. The place I landed was that if you needed to use `pkgs` like that then things should be pinned, and instead of using `info = ./package.nix`, you instead expose the package as a flake output, and add the package to the package set that way, like I do [here](https://github.com/purs-nix/purs-nix/blob/18c1cae603b876c62515b7e4a3d4b587119e006b/namespaces/ursi.nix#L37). What are you thoughts on that?

**Comment by klarkc** [comment]
Humm I agree, this is a lot better, and thinking about that, now I can't see a reason for having a `/package.nix` instead of using flake.nix everywhere, there is a reason for that?

**Comment by ursi** [comment]
Well, the `package.nix` approach has the advantage of not needing to fetch other dependencies. That's the only benefit I can think of at the moment. If you start including tons of flake-based dependencies, it could start to download a lot of things. I'm not really sure though how much of an impact it would have, but it could be the case that it actually *is* best to just pass `pkgs` to the `package.nix` like you suggested.

**Comment by klarkc** [comment]
@ursi there is already a way of optimizing nixpkgs at least, using `nixpkgs.follows`. I believe [niv](https://github.com/nmattia/niv) also uses this pattern of passing pkgs as parameter.

**Comment by ursi** [comment]
Oh, yes, if you grab the packages from the source as a flake input, you can override their inputs to help with that. But if you grab them from the package set, there currently is no mechanism for for that.
